-- =========================================================
-- Wypełnienie tabeli produktów SIBO (350 unikalnych wierszy)
-- =========================================================
DROP TABLE IF EXISTS sibo_produkty CASCADE;
CREATE TABLE IF NOT EXISTS sibo_produkty (
    id SERIAL PRIMARY KEY,
    rodzaj VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('dozwolone', 'umiarkowane', 'zakazane')),
    ilosc NUMERIC(10, 2) NULL,
    jednostka VARCHAR(50) NULL,
    komentarz TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sibo_produkty_rodzaj ON sibo_produkty(rodzaj);
CREATE INDEX IF NOT EXISTS idx_sibo_produkty_status ON sibo_produkty(status);

INSERT INTO sibo_produkty (rodzaj, status, ilosc, jednostka, komentarz) VALUES
('pieczywo pszenne zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo pszenne pełnoziarniste', 'zakazane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) pełnoziarniste', 'zakazane', NULL, NULL, NULL),
('pieczywo 100% żytnie na zakwasie', 'zakazane', NULL, NULL, NULL),
('pieczywo 100% żytnie pełnoziarniste na zakwasie', 'zakazane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na drożdżach', 'zakazane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na zakwasie', 'umiarkowane', 60.0, 'g', NULL),
('pieczywo naturalnie bezglutenowe na zakwasie', 'dozwolone', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na drożdżach', 'dozwolone', NULL, NULL, NULL),
('pieczywo mieszane z dodatkami (orzechy, nasiona)', 'zakazane', NULL, NULL, NULL),
('domowy chleb wg przepisu', 'dozwolone', NULL, NULL, NULL),
('pszenica', 'zakazane', NULL, NULL, NULL),
('orkisz', 'zakazane', NULL, NULL, NULL),
('płaskurka', 'zakazane', NULL, NULL, NULL),
('samopsza', 'zakazane', NULL, NULL, NULL),
('żyto', 'zakazane', NULL, NULL, NULL),
('jęczmień', 'zakazane', NULL, NULL, NULL),
('owies', 'umiarkowane', NULL, NULL, NULL),
('owies bezglutenowy', 'umiarkowane', NULL, NULL, NULL),
('pszenżyto', 'zakazane', NULL, NULL, NULL),
('kukurydza', 'umiarkowane', 40.0, 'g', NULL),
('gryka', 'dozwolone', NULL, NULL, NULL),
('proso', 'dozwolone', NULL, NULL, NULL),
('kasza manna', 'zakazane', NULL, NULL, NULL),
('kasza kuskus', 'zakazane', NULL, NULL, NULL),
('kasza bulgur', 'zakazane', NULL, NULL, NULL),
('kasza pęczak', 'zakazane', NULL, NULL, NULL),
('kasza perłowa', 'zakazane', NULL, NULL, NULL),
('kasza gryczana biała', 'umiarkowane', 50.0, 'g', NULL),
('kasza gryczana palona', 'umiarkowane', 50.0, 'g', NULL),
('kasza jaglana', 'dozwolone', NULL, NULL, NULL),
('płatki owsiane błyskawiczne', 'umiarkowane', 20.0, 'g', NULL),
('płatki owsiane górskie', 'umiarkowane', 50.0, 'g', NULL),
('płatki owsiane zwykłe', 'umiarkowane', 50.0, 'g', NULL),
('płatki owsiane bezglutenowe', 'umiarkowane', 70.0, 'g', NULL),
('otręby owsiane', 'umiarkowane', 20.0, 'g', NULL),
('ryż biały', 'dozwolone', NULL, NULL, NULL),
('ryż brązowy pełnoziarnisty', 'umiarkowane', 70.0, 'g', NULL),
('ryż basmati', 'dozwolone', NULL, NULL, NULL),
('amarantus', 'zakazane', NULL, NULL, NULL),
('komosa ryżowa (quinoa)', 'umiarkowane', 50.0, 'g', NULL),
('makaron pełnoziarnisty z pszenicy', 'zakazane', NULL, NULL, NULL),
('makaron orkiszowy', 'zakazane', NULL, NULL, NULL),
('makaron kukurydziany', 'dozwolone', NULL, NULL, NULL),
('makaron ryżowy', 'dozwolone', NULL, NULL, NULL),
('makaron gryczany', 'umiarkowane', 60.0, 'g', NULL),
('makaron z soczewicy', 'umiarkowane', 45.0, 'g', NULL),
('makaron z ciecierzycy', 'umiarkowane', 45.0, 'g', NULL),
('makaron z komosy ryżowej', 'umiarkowane', 60.0, 'g', NULL),
('makaron z fasoli', 'zakazane', NULL, NULL, NULL),
('jaja kurze', 'dozwolone', NULL, NULL, NULL),
('jaja przepiórcze', 'dozwolone', NULL, NULL, NULL),
('jogurt naturalny', 'zakazane', NULL, NULL, NULL),
('jogurt naturalny bez laktozy', 'umiarkowane', 200.0, 'g', NULL),
('jogurt owocowy', 'zakazane', NULL, NULL, NULL),
('jogurt owocowy bez laktozy', 'umiarkowane', 200.0, 'g', 'tylko truskawki i jagody, bez SGF'),
('jogurt kokosowy wegański', 'umiarkowane', 150.0, 'g', 'bez SGF'),
('kefir', 'zakazane', NULL, NULL, NULL),
('kefir bez laktozy', 'dozwolone', NULL, NULL, NULL),
('masło', 'dozwolone', NULL, NULL, NULL),
('masło bez laktozy', 'dozwolone', NULL, NULL, NULL),
('masło klarowane', 'dozwolone', NULL, NULL, NULL),
('maślanka naturalna', 'zakazane', NULL, NULL, NULL),
('mleko kozie', 'umiarkowane', 30.0, 'ml', NULL),
('mleko krowie', 'zakazane', NULL, NULL, NULL),
('mleko krowie bez laktozy', 'umiarkowane', 250.0, 'ml', NULL),
('mleko owcze', 'zakazane', NULL, NULL, NULL),
('mleko skondensowane niesłodzone', 'zakazane', NULL, NULL, NULL),
('mleko skondensowane słodzone', 'zakazane', NULL, NULL, NULL),
('mleko w proszku', 'zakazane', NULL, NULL, NULL),
('mleko w proszku bez laktozy', 'dozwolone', NULL, NULL, NULL),
('mleko zsiadłe', 'zakazane', NULL, NULL, NULL),
('mleko migdałowe/napój migdałowy', 'dozwolone', NULL, NULL, NULL),
('mleko ryżowe', 'dozwolone', NULL, NULL, NULL),
('mleko owsiane/napój owsiany', 'zakazane', NULL, NULL, NULL),
('mleko kokosowe/napój kokosowy', 'dozwolone', NULL, NULL, NULL),
('mleko sojowe z izolatu białka sojowego', 'dozwolone', NULL, NULL, NULL),
('mleko sojowe z całych ziaren', 'zakazane', NULL, NULL, NULL),
('mleko makadamia', 'dozwolone', NULL, NULL, NULL),
('mleko z nerkowców', 'zakazane', NULL, NULL, NULL),
('oscypek/sery wędzone', 'umiarkowane', NULL, NULL, NULL),
('ricotta', 'umiarkowane', 40.0, 'g', NULL),
('ricotta bez laktozy', 'dozwolone', NULL, NULL, NULL),
('ser capri (typ włoski)', 'zakazane', NULL, NULL, NULL),
('ser feta', 'umiarkowane', 40.0, 'g', NULL),
('ser feta bez laktozy', 'dozwolone', NULL, NULL, NULL),
('ser mascarpone', 'umiarkowane', 40.0, 'g', NULL),
('ser mozzarella', 'umiarkowane', 40.0, 'g', NULL),
('ser mozzarella bez laktozy', 'dozwolone', NULL, NULL, NULL),
('ser śmietankowy', 'umiarkowane', 40.0, 'g', NULL),
('ser śmietankowy bez laktozy', 'dozwolone', NULL, NULL, NULL),
('serek fromage (do smarowania)', 'zakazane', NULL, NULL, NULL),
('serek homogenizowany naturalny', 'zakazane', NULL, NULL, NULL),
('serek homogenizowany waniliowy, owocowy', 'zakazane', NULL, NULL, NULL),
('serek topiony', 'zakazane', NULL, NULL, NULL),
('serek wiejski', 'umiarkowane', 50.0, 'g', NULL),
('serek wiejski bez laktozy', 'dozwolone', NULL, NULL, NULL),
('serwatka', 'zakazane', NULL, NULL, NULL),
('sery pleśniowe', 'umiarkowane', 40.0, 'g', NULL),
('sery twarde z mleka krowiego', 'dozwolone', NULL, NULL, NULL),
('sery twarde z mleka koziego', 'dozwolone', NULL, NULL, NULL),
('ser parmezan', 'dozwolone', NULL, NULL, NULL),
('skyr', 'zakazane', NULL, NULL, NULL),
('skyr bez laktozy', 'dozwolone', NULL, NULL, NULL),
('śmietana kwaśna', 'umiarkowane', 30.0, 'g', NULL),
('śmietana kwaśna bez laktozy', 'dozwolone', NULL, NULL, NULL),
('śmietanka słodka', 'umiarkowane', 30.0, 'g', NULL),
('śmietanka słodka bez laktozy', 'dozwolone', NULL, NULL, NULL),
('tofu miękkie', 'zakazane', NULL, NULL, NULL),
('tofu twarde', 'dozwolone', NULL, NULL, NULL),
('twaróg', 'zakazane', NULL, NULL, NULL),
('twaróg bez laktozy', 'dozwolone', NULL, NULL, NULL),
('baranina/jagnięcina', 'dozwolone', NULL, NULL, NULL),
('cielęcina', 'dozwolone', NULL, NULL, NULL),
('dziczyzna', 'dozwolone', NULL, NULL, NULL),
('gęś', 'dozwolone', NULL, NULL, NULL),
('indyk', 'dozwolone', NULL, NULL, NULL),
('kaczka', 'dozwolone', NULL, NULL, NULL),
('królik', 'dozwolone', NULL, NULL, NULL),
('kurczak', 'dozwolone', NULL, NULL, NULL),
('perliczka', 'dozwolone', NULL, NULL, NULL),
('przepiórka', 'dozwolone', NULL, NULL, NULL),
('wieprzowina', 'dozwolone', NULL, NULL, NULL),
('wołowina', 'dozwolone', NULL, NULL, NULL),
('kabanosy', 'zakazane', NULL, NULL, NULL),
('kaszanka jęczmienna', 'zakazane', NULL, NULL, NULL),
('kaszanka gryczana', 'zakazane', NULL, NULL, NULL),
('kaszanka bezglutenowa', 'zakazane', NULL, NULL, NULL),
('kiełbasa wieprzowa/mieszana', 'zakazane', NULL, NULL, NULL),
('kiełbasa drobiowa', 'zakazane', NULL, NULL, NULL),
('kiełbasa bezglutenowa', 'zakazane', NULL, NULL, NULL),
('kindziuk', 'umiarkowane', NULL, NULL, 'bez czosnku'),
('leberka (wątrobianka, pasztetowa)', 'zakazane', NULL, NULL, NULL),
('pasztet', 'zakazane', NULL, NULL, NULL),
('polędwica sopocka', 'umiarkowane', NULL, NULL, 'bez aromatów, białka sojowego'),
('salceson', 'zakazane', NULL, NULL, NULL),
('salami', 'umiarkowane', 15.0, 'g', 'bez czosnku i cebuli'),
('suszone mięsa', 'umiarkowane', NULL, NULL, 'bez czosnku i cebuli'),
('szynka gotowana i parzona', 'umiarkowane', NULL, NULL, 'bez aromatów, przypraw, białka sojowego'),
('szynka długodojrzewająca', 'umiarkowane', NULL, NULL, 'w składzie tylko mięso i sól'),
('wędzone mięsa', 'umiarkowane', NULL, NULL, 'bez dodatków, aromatów'),
('dorada', 'dozwolone', NULL, NULL, NULL),
('dorsz', 'dozwolone', NULL, NULL, NULL),
('flądra', 'dozwolone', NULL, NULL, NULL),
('halibut świeży', 'dozwolone', NULL, NULL, NULL),
('halibut wędzony', 'dozwolone', NULL, NULL, NULL),
('jesiotr', 'dozwolone', NULL, NULL, NULL),
('karp', 'dozwolone', NULL, NULL, NULL),
('lin', 'dozwolone', NULL, NULL, NULL),
('łosoś świeży', 'dozwolone', NULL, NULL, NULL),
('łosoś wędzony', 'dozwolone', NULL, NULL, NULL),
('makrela wędzona', 'dozwolone', NULL, NULL, NULL),
('miętus', 'dozwolone', NULL, NULL, NULL),
('mintaj', 'dozwolone', NULL, NULL, NULL),
('miruna', 'dozwolone', NULL, NULL, NULL),
('morszczuk', 'dozwolone', NULL, NULL, NULL),
('okoń', 'dozwolone', NULL, NULL, NULL),
('pstrąg świeży', 'dozwolone', NULL, NULL, NULL),
('pstrąg wędzony', 'dozwolone', NULL, NULL, NULL),
('sandacz', 'dozwolone', NULL, NULL, NULL),
('sardynki świeże', 'dozwolone', NULL, NULL, NULL),
('sardynki w oleju/sosie pomidorowym', 'umiarkowane', NULL, NULL, 'bez dodatku czosnku, cebuli i aromatów'),
('sardynki wędzone', 'dozwolone', NULL, NULL, NULL),
('sola', 'dozwolone', NULL, NULL, NULL),
('szczupak', 'dozwolone', NULL, NULL, NULL),
('szprotki wędzone', 'dozwolone', NULL, NULL, NULL),
('szprotki w oleju/w sosie pomidorowym', 'umiarkowane', NULL, NULL, 'bez dodatku czosnku, cebuli i aromatów'),
('śledź', 'dozwolone', NULL, NULL, NULL),
('śledź w occie w zalewie z cebulą', 'zakazane', NULL, NULL, NULL),
('śledź w occie w zalewie bez cebuli', 'dozwolone', NULL, NULL, NULL),
('śledź w oleju w zalewie z cebulą', 'zakazane', NULL, NULL, NULL),
('śledź w oleju w zalewie bez cebuli', 'dozwolone', NULL, NULL, NULL),
('tuńczyk świeży', 'dozwolone', NULL, NULL, NULL),
('tuńczyk w puszce w sosie własnym', 'dozwolone', NULL, NULL, NULL),
('tuńczyk w puszce w oleju', 'dozwolone', NULL, NULL, NULL),
('węgorz wędzony', 'umiarkowane', NULL, NULL, 'bez dodatku czosnku, cebuli i aromatów'),
('kalmary', 'dozwolone', NULL, NULL, NULL),
('krewetki', 'dozwolone', NULL, NULL, NULL),
('małże', 'dozwolone', NULL, NULL, NULL),
('ostrygi', 'dozwolone', NULL, NULL, NULL),
('ośmiornice', 'dozwolone', NULL, NULL, NULL),
('przegrzebki (muszle św. Jakuba)', 'dozwolone', NULL, NULL, NULL),
('acerola', 'zakazane', NULL, NULL, NULL),
('agrest', 'umiarkowane', 20.0, 'g', NULL),
('ananas', 'umiarkowane', 140.0, 'g', 'wyłącznie świeży'),
('arbuz', 'zakazane', NULL, NULL, NULL),
('aronia', 'zakazane', NULL, NULL, NULL),
('awokado', 'umiarkowane', 30.0, 'g', NULL),
('banan niedojrzały', 'umiarkowane', 100.0, 'g', NULL),
('banan dojrzały', 'zakazane', NULL, NULL, NULL),
('borówka amerykańska', 'umiarkowane', 120.0, 'g', NULL),
('borówka czerwona', 'umiarkowane', 130.0, 'g', NULL),
('brzoskwinia', 'zakazane', NULL, NULL, NULL),
('cytryna', 'dozwolone', NULL, NULL, NULL),
('czarna porzeczka', 'umiarkowane', 15.0, 'g', NULL),
('czereśnia', 'zakazane', NULL, NULL, NULL),
('czerwona porzeczka', 'umiarkowane', 20.0, 'g', NULL),
('daktyle suszone', 'zakazane', NULL, NULL, NULL),
('dzika róża (owoc)', 'zakazane', NULL, NULL, NULL),
('figi', 'zakazane', NULL, NULL, NULL),
('grapefruit', 'umiarkowane', 80.0, 'g', NULL),
('granat', 'umiarkowane', 45.0, 'g', NULL),
('gruszka', 'zakazane', NULL, NULL, NULL),
('jabłko', 'zakazane', NULL, NULL, NULL),
('jagody czarne', 'dozwolone', NULL, NULL, NULL),
('jagody goji', 'umiarkowane', 10.0, 'g', NULL),
('jeżyna', 'zakazane', NULL, NULL, NULL),
('kaki', 'zakazane', NULL, NULL, NULL),
('kiwi', 'umiarkowane', 150.0, 'g', NULL),
('kokos', 'umiarkowane', 30.0, 'g', NULL),
('liczi', 'zakazane', NULL, NULL, NULL),
('limonka', 'dozwolone', NULL, NULL, NULL),
('malina', 'umiarkowane', 60.0, 'g', NULL),
('mandarynka', 'umiarkowane', 130.0, 'g', NULL),
('mango', 'zakazane', NULL, NULL, NULL),
('melon', 'umiarkowane', 100.0, 'g', NULL),
('morela', 'zakazane', NULL, NULL, NULL),
('morwa', 'zakazane', NULL, NULL, NULL),
('nektarynka', 'zakazane', NULL, NULL, NULL),
('papaja', 'umiarkowane', 140.0, 'g', NULL),
('pigwa', 'zakazane', NULL, NULL, NULL),
('pomarańcza', 'umiarkowane', 200.0, 'g', NULL),
('pomelo', 'zakazane', NULL, NULL, NULL),
('porzeczka', 'zakazane', NULL, NULL, NULL),
('poziomka', 'zakazane', NULL, NULL, NULL),
('rabarbar', 'dozwolone', NULL, NULL, NULL),
('rodzynki', 'zakazane', NULL, NULL, NULL),
('rokitnik', 'zakazane', NULL, NULL, NULL),
('smoczy owoc (pitaja)', 'umiarkowane', 200.0, 'g', NULL),
('śliwka', 'zakazane', NULL, NULL, NULL),
('śliwka suszona', 'zakazane', NULL, NULL, NULL),
('truskawka', 'umiarkowane', 65.0, 'g', NULL),
('winogrona', 'umiarkowane', 50.0, 'g', NULL),
('wiśnia', 'zakazane', NULL, NULL, NULL),
('żurawina świeża/mrożona', 'umiarkowane', 130.0, 'g', NULL),
('żurawina suszona', 'umiarkowane', 15.0, 'g', NULL),
('batat', 'umiarkowane', 75.0, 'g', NULL),
('bakłażan', 'umiarkowane', 75.0, 'g', NULL),
('boczniak', 'umiarkowane', 75.0, 'g', NULL),
('bób', 'zakazane', NULL, NULL, NULL),
('botwinka/boćwina', 'dozwolone', NULL, NULL, NULL),
('brokuł', 'umiarkowane', 75.0, 'g', 'same różyczki'),
('brukiew', 'umiarkowane', 75.0, 'g', NULL),
('brukselka', 'zakazane', NULL, NULL, NULL),
('burak', 'umiarkowane', 25.0, 'g', NULL),
('burak marynowany (w occie)', 'umiarkowane', 75.0, 'g', NULL),
('cebula', 'zakazane', NULL, NULL, NULL),
('chrzan', 'umiarkowane', 30.0, 'g', 'bez dodatków'),
('cukinia', 'umiarkowane', 70.0, 'g', NULL),
('cykoria', 'dozwolone', NULL, NULL, NULL),
('czosnek', 'zakazane', NULL, NULL, NULL),
('dynia hokkaido', 'umiarkowane', 75.0, 'g', NULL),
('dynia piżmowa', 'zakazane', NULL, NULL, NULL),
('fasola (nasiona)', 'zakazane', NULL, NULL, NULL),
('groch łuskany żółty', 'zakazane', NULL, NULL, NULL),
('grzyby', 'zakazane', NULL, NULL, NULL),
('imbir', 'dozwolone', NULL, NULL, NULL),
('jarmuż', 'umiarkowane', 75.0, 'g', NULL),
('kalafior', 'zakazane', NULL, NULL, NULL),
('kalarepa', 'umiarkowane', 75.0, 'g', NULL),
('kapusta', 'umiarkowane', 75.0, 'g', NULL),
('kapusta kiszona', 'umiarkowane', 20.0, 'g', NULL),
('karczoch', 'zakazane', NULL, NULL, NULL),
('kiełki brokuła', 'dozwolone', NULL, NULL, NULL),
('kiełki rzodkiewki', 'dozwolone', NULL, NULL, NULL),
('kiełki fasoli mung', 'dozwolone', NULL, NULL, NULL),
('koper włoski', 'umiarkowane', 45.0, 'g', NULL),
('kukurydza z puszki konserwowa', 'umiarkowane', 75.0, 'g', NULL),
('kurki', 'zakazane', NULL, NULL, NULL),
('marchew surowa', 'dozwolone', NULL, NULL, NULL),
('marchew gotowana', 'dozwolone', NULL, NULL, NULL),
('ogórek', 'dozwolone', NULL, NULL, NULL),
('ogórek kiszony', 'umiarkowane', 40.0, 'g', NULL),
('ogórek konserwowy w occie', 'umiarkowane', 75.0, 'g', NULL),
('oliwki', 'dozwolone', NULL, NULL, NULL),
('pak choi', 'umiarkowane', 75.0, 'g', NULL),
('papryka chili', 'umiarkowane', 10.0, 'g', NULL),
('papryka czerwona', 'umiarkowane', 40.0, 'g', NULL),
('papryka żółta', 'umiarkowane', 40.0, 'g', NULL),
('papryka zielona', 'umiarkowane', 75.0, 'g', NULL),
('pasternak', 'dozwolone', NULL, NULL, NULL),
('pieczarki', 'zakazane', NULL, NULL, NULL),
('pieczarki marynowane', 'umiarkowane', 75.0, 'g', NULL),
('pietruszka korzeń', 'umiarkowane', 75.0, 'g', NULL),
('pietruszka natka', 'dozwolone', NULL, NULL, NULL),
('pomidor', 'umiarkowane', 70.0, 'g', NULL),
('pomidor cherry', 'umiarkowane', 45.0, 'g', NULL),
('por', 'zakazane', NULL, NULL, NULL),
('roszponka', 'dozwolone', NULL, NULL, NULL),
('rzepa', 'dozwolone', NULL, NULL, NULL),
('rukola', 'dozwolone', NULL, NULL, NULL),
('rzodkiew biała', 'dozwolone', NULL, NULL, NULL),
('rzodkiewka', 'dozwolone', NULL, NULL, NULL),
('sałata głowiasta', 'dozwolone', NULL, NULL, NULL),
('sałata lodowa', 'dozwolone', NULL, NULL, NULL),
('sałata rzymska', 'dozwolone', NULL, NULL, NULL),
('seler', 'umiarkowane', 75.0, 'g', NULL),
('seler naciowy', 'umiarkowane', 10.0, 'g', NULL),
('soczewica', 'umiarkowane', 45.0, 'g', 'wyłącznie ze słoika/puszki, wypłukana'),
('soja', 'zakazane', NULL, NULL, NULL),
('szczaw', 'zakazane', NULL, NULL, NULL),
('szczypiorek', 'dozwolone', NULL, NULL, NULL),
('szparagi', 'zakazane', NULL, NULL, NULL),
('szalotka', 'zakazane', NULL, NULL, NULL),
('szpinak dojrzały', 'dozwolone', NULL, NULL, NULL),
('szpinak baby', 'umiarkowane', 75.0, 'g', NULL),
('topinambur', 'umiarkowane', NULL, NULL, NULL),
('zielona fasolka', 'umiarkowane', 75.0, 'g', NULL),
('zielony groszek', 'dozwolone', NULL, NULL, NULL),
('ziemniak', 'dozwolone', NULL, NULL, NULL),
('ciecierzyca', 'umiarkowane', 40.0, 'g', 'wyłącznie ze słoika/puszki, wypłukana'),
('groch', 'dozwolone', NULL, NULL, NULL),
('fasola typu Jaś', 'dozwolone', NULL, NULL, NULL),
('orzech ziemny', 'umiarkowane', 30.0, 'g', NULL),
('masło orzechowe z orzechów ziemnych', 'umiarkowane', 30.0, 'g', NULL),
('nasiona pestki słonecznika', 'umiarkowane', 30.0, 'g', NULL),
('migdały', 'umiarkowane', 15.0, 'g', NULL),
('pestki dyni', 'umiarkowane', 30.0, 'g', NULL),
('ziarno kakaowca (czekolada, kakao)', 'umiarkowane', 15.0, 'g', NULL),
('orzech włoski', 'umiarkowane', 30.0, 'g', NULL),
('orzech laskowy', 'umiarkowane', 15.0, 'g', NULL),
('orzech kokosowy (wiórki)', 'umiarkowane', 30.0, 'g', NULL),
('orzech nerkowca', 'zakazane', NULL, NULL, NULL),
('orzech brazylijski', 'umiarkowane', 30.0, 'g', NULL),
('orzech pistacjowy', 'zakazane', NULL, NULL, NULL),
('orzech makadamia', 'umiarkowane', 40.0, 'g', NULL),
('orzech pecan', 'umiarkowane', 30.0, 'g', NULL),
('herbata czarna', 'dozwolone', NULL, NULL, NULL),
('pokrzywa zwyczajna', 'dozwolone', NULL, NULL, NULL),
('sok pomarańczowy', 'umiarkowane', 100.0, 'ml', 'wyłącznie świeżo wyciskany'),
('sok pomidorowy', 'umiarkowane', 100.0, 'ml', 'bez dodatku czosnku i cebuli'),
('napoje energetyczne (energetyki)', 'zakazane', NULL, NULL, NULL),
('napoje czekoladowe', 'zakazane', NULL, NULL, NULL),
('napoje kakaowe', 'zakazane', NULL, NULL, NULL),
('gorąca czekolada', 'zakazane', NULL, NULL, NULL),
('piwo', 'zakazane', NULL, NULL, NULL),
('brandy', 'umiarkowane', 30.0, 'ml', NULL),
('rum', 'zakazane', NULL, NULL, NULL),
('wino białe', 'umiarkowane', 150.0, 'ml', 'wyłącznie wytrawne'),
('wino różowe', 'umiarkowane', 150.0, 'ml', 'wyłącznie wytrawne'),
('wino czerwone', 'umiarkowane', 150.0, 'ml', 'wyłącznie wytrawne'),
('wino musujące (prosecco, szampan, cava)', 'umiarkowane', 150.0, 'ml', 'wyłącznie wytrawne/brut'),
('wódka', 'umiarkowane', 30.0, 'ml', 'czysta, bez słodkich dodatków'),
('spirytus', 'zakazane', NULL, NULL, NULL),
('ocet', 'dozwolone', NULL, NULL, NULL),
('sos sojowy', 'umiarkowane', 30.0, 'ml', NULL),
('olej o smaku czosnkowym', 'dozwolone', NULL, NULL, NULL),
('SGF (syrop glukozowo-fruktozowy)', 'zakazane', NULL, NULL, NULL),
('sól z antyzbrylaczem', 'zakazane', NULL, NULL, NULL);
