-- =========================================================
-- Wypełnienie tabeli produktów Hashimoto (351 unikalnych wierszy)
-- =========================================================
DROP TABLE IF EXISTS hashimoto_produkty CASCADE;
CREATE TABLE IF NOT EXISTS hashimoto_produkty (
    id SERIAL PRIMARY KEY,
    rodzaj VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('dozwolone', 'umiarkowane', 'zakazane')),
    ilosc NUMERIC(10, 2) NULL,
    jednostka VARCHAR(50) NULL,
    komentarz TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_hashimoto_produkty_rodzaj ON hashimoto_produkty(rodzaj);
CREATE INDEX IF NOT EXISTS idx_hashimoto_produkty_status ON hashimoto_produkty(status);

INSERT INTO hashimoto_produkty (rodzaj, status, ilosc, jednostka, komentarz) VALUES
('pieczywo', 'zakazane', NULL, NULL, NULL),
('pieczywo pszenne zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo pszenne pełnoziarniste', 'zakazane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) pełnoziarniste', 'zakazane', NULL, NULL, NULL),
('pieczywo 100% żytnie na zakwasie', 'zakazane', NULL, NULL, NULL),
('pieczywo 100% żytnie pełnoziarniste na zakwasie', 'umiarkowane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na drożdżach', 'umiarkowane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na zakwasie', 'umiarkowane', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na zakwasie', 'dozwolone', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na drożdżach', 'dozwolone', NULL, NULL, NULL),
('pieczywo mieszane z dodatkami (orzechy, nasiona)', 'zakazane', NULL, NULL, NULL),
('domowy chleb wg przepisu', 'dozwolone', NULL, NULL, NULL),
('pszenica', 'zakazane', NULL, NULL, NULL),
('orkisz', 'umiarkowane', NULL, NULL, NULL),
('płaskurka', 'umiarkowane', NULL, NULL, NULL),
('samopsza', 'umiarkowane', NULL, NULL, NULL),
('żyto', 'umiarkowane', NULL, NULL, NULL),
('jęczmień', 'zakazane', NULL, NULL, NULL),
('owies', 'umiarkowane', NULL, NULL, NULL),
('owies bezglutenowy', 'dozwolone', NULL, NULL, NULL),
('pszenżyto', 'zakazane', NULL, NULL, NULL),
('kukurydza', 'dozwolone', NULL, NULL, NULL),
('gryka', 'dozwolone', NULL, NULL, NULL),
('proso', 'dozwolone', NULL, NULL, NULL),
('kasza manna', 'zakazane', NULL, NULL, NULL),
('kasza kuskus', 'zakazane', NULL, NULL, NULL),
('kasza bulgur', 'zakazane', NULL, NULL, NULL),
('kasza pęczak', 'zakazane', NULL, NULL, NULL),
('kasza perłowa', 'zakazane', NULL, NULL, NULL),
('kasza gryczana biała', 'dozwolone', NULL, NULL, NULL),
('kasza gryczana palona', 'dozwolone', NULL, NULL, NULL),
('kasza jaglana', 'umiarkowane', NULL, NULL, NULL),
('płatki owsiane błyskawiczne', 'zakazane', NULL, NULL, NULL),
('płatki owsiane górskie', 'umiarkowane', NULL, NULL, NULL),
('płatki owsiane zwykłe', 'umiarkowane', NULL, NULL, NULL),
('płatki owsiane bezglutenowe', 'dozwolone', NULL, NULL, NULL),
('otręby owsiane', 'umiarkowane', NULL, NULL, NULL),
('ryż biały', 'umiarkowane', NULL, NULL, NULL),
('ryż brązowy pełnoziarnisty', 'dozwolone', NULL, NULL, NULL),
('ryż basmati', 'dozwolone', NULL, NULL, NULL),
('amarantus', 'dozwolone', NULL, NULL, NULL),
('komosa ryżowa (quinoa)', 'dozwolone', NULL, NULL, NULL),
('makaron pełnoziarnisty z pszenicy', 'zakazane', NULL, NULL, NULL),
('makaron orkiszowy', 'umiarkowane', NULL, NULL, NULL),
('makaron kukurydziany', 'dozwolone', NULL, NULL, NULL),
('makaron ryżowy', 'dozwolone', NULL, NULL, NULL),
('makaron gryczany', 'dozwolone', NULL, NULL, NULL),
('makaron z soczewicy', 'dozwolone', NULL, NULL, NULL),
('makaron z ciecierzycy', 'dozwolone', NULL, NULL, NULL),
('makaron z komosy ryżowej', 'dozwolone', NULL, NULL, NULL),
('makaron z fasoli', 'dozwolone', NULL, NULL, NULL),
('jaja kurze', 'dozwolone', NULL, NULL, NULL),
('jaja przepiórcze', 'dozwolone', NULL, NULL, NULL),
('jogurt naturalny', 'umiarkowane', NULL, NULL, NULL),
('jogurt naturalny bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('jogurt owocowy', 'umiarkowane', NULL, NULL, NULL),
('jogurt owocowy bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('jogurt kokosowy wegański', 'dozwolone', NULL, NULL, NULL),
('kefir', 'umiarkowane', NULL, NULL, NULL),
('kefir bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('masło', 'dozwolone', NULL, NULL, NULL),
('masło bez laktozy', 'dozwolone', NULL, NULL, NULL),
('masło klarowane', 'dozwolone', NULL, NULL, NULL),
('maślanka naturalna', 'umiarkowane', NULL, NULL, NULL),
('mleko kozie', 'umiarkowane', NULL, NULL, NULL),
('mleko krowie', 'umiarkowane', NULL, NULL, NULL),
('mleko krowie bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('mleko owcze', 'umiarkowane', NULL, NULL, NULL),
('mleko skondensowane niesłodzone', 'zakazane', NULL, NULL, NULL),
('mleko skondensowane słodzone', 'zakazane', NULL, NULL, NULL),
('mleko w proszku', 'zakazane', NULL, NULL, NULL),
('mleko w proszku bez laktozy', 'zakazane', NULL, NULL, NULL),
('mleko zsiadłe', 'umiarkowane', NULL, NULL, NULL),
('mleko migdałowe/napój migdałowy', 'dozwolone', NULL, NULL, NULL),
('mleko ryżowe', 'dozwolone', NULL, NULL, NULL),
('mleko owsiane/napój owsiany', 'umiarkowane', NULL, NULL, NULL),
('mleko kokosowe/napój kokosowy', 'dozwolone', NULL, NULL, NULL),
('mleko sojowe z izolatu białka sojowego', 'zakazane', NULL, NULL, NULL),
('mleko sojowe z całych ziaren', 'zakazane', NULL, NULL, NULL),
('mleko makadamia', 'dozwolone', NULL, NULL, NULL),
('mleko z nerkowców', 'dozwolone', NULL, NULL, NULL),
('oscypek/sery wędzone', 'umiarkowane', NULL, NULL, NULL),
('ricotta', 'umiarkowane', NULL, NULL, NULL),
('ricotta bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('ser capri (typ włoski)', 'umiarkowane', NULL, NULL, NULL),
('ser feta', 'dozwolone', NULL, NULL, NULL),
('ser feta bez laktozy', 'dozwolone', NULL, NULL, NULL),
('ser mascarpone', 'umiarkowane', NULL, NULL, NULL),
('ser mozzarella', 'umiarkowane', NULL, NULL, NULL),
('ser mozzarella bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('ser śmietankowy', 'umiarkowane', NULL, NULL, NULL),
('ser śmietankowy bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('serek fromage (do smarowania)', 'umiarkowane', NULL, NULL, NULL),
('serek homogenizowany naturalny', 'umiarkowane', NULL, NULL, NULL),
('serek homogenizowany waniliowy, owocowy', 'umiarkowane', NULL, NULL, NULL),
('serek topiony', 'umiarkowane', NULL, NULL, NULL),
('serek wiejski', 'umiarkowane', NULL, NULL, NULL),
('serek wiejski bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('serwatka', 'umiarkowane', NULL, NULL, NULL),
('sery pleśniowe', 'umiarkowane', NULL, NULL, NULL),
('sery twarde z mleka krowiego', 'umiarkowane', NULL, NULL, NULL),
('sery twarde z mleka koziego', 'dozwolone', NULL, NULL, NULL),
('ser parmezan', 'umiarkowane', NULL, NULL, NULL),
('skyr', 'umiarkowane', NULL, NULL, NULL),
('skyr bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('śmietana kwaśna', 'umiarkowane', NULL, NULL, NULL),
('śmietana kwaśna bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('śmietanka słodka', 'umiarkowane', NULL, NULL, NULL),
('śmietanka słodka bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('tofu miękkie', 'umiarkowane', 120.0, 'g', 'Min 4 h od przyjęcia lewotyroksyny'),
('tofu twarde', 'umiarkowane', 80.0, 'g', 'Min 4 h od przyjęcia lewotyroksyny'),
('twaróg', 'umiarkowane', NULL, NULL, NULL),
('twaróg bez laktozy', 'umiarkowane', NULL, NULL, NULL),
('baranina/jagnięcina', 'dozwolone', NULL, NULL, NULL),
('cielęcina', 'dozwolone', NULL, NULL, NULL),
('dziczyzna', 'dozwolone', NULL, NULL, NULL),
('gęś', 'dozwolone', NULL, NULL, NULL),
('indyk', 'dozwolone', NULL, NULL, NULL),
('kaczka', 'dozwolone', NULL, NULL, NULL),
('królik', 'dozwolone', NULL, NULL, NULL),
('kurczak', 'dozwolone', NULL, NULL, NULL),
('perliczka', 'dozwolone', NULL, NULL, NULL),
('przepiórka', 'dozwolone', NULL, NULL, NULL),
('wieprzowina', 'dozwolone', NULL, NULL, NULL),
('wołowina', 'dozwolone', NULL, NULL, NULL),
('kabanosy', 'dozwolone', NULL, NULL, NULL),
('kaszanka jęczmienna', 'zakazane', NULL, NULL, NULL),
('kaszanka gryczana', 'dozwolone', NULL, NULL, NULL),
('kaszanka bezglutenowa', 'dozwolone', NULL, NULL, NULL),
('kiełbasa wieprzowa/mieszana', 'umiarkowane', NULL, NULL, NULL),
('kiełbasa drobiowa', 'umiarkowane', NULL, NULL, NULL),
('kiełbasa bezglutenowa', 'dozwolone', NULL, NULL, NULL),
('kindziuk', 'dozwolone', NULL, NULL, NULL),
('leberka (wątrobianka, pasztetowa)', 'zakazane', NULL, NULL, NULL),
('pasztet', 'zakazane', NULL, NULL, NULL),
('polędwica sopocka', 'dozwolone', NULL, NULL, NULL),
('salceson', 'dozwolone', NULL, NULL, NULL),
('salami', 'dozwolone', NULL, NULL, NULL),
('suszone mięsa', 'dozwolone', NULL, NULL, NULL),
('szynka gotowana i parzona', 'dozwolone', NULL, NULL, NULL),
('szynka długodojrzewająca', 'dozwolone', NULL, NULL, NULL),
('wędzone mięsa', 'dozwolone', NULL, NULL, NULL),
('dorada', 'dozwolone', NULL, NULL, NULL),
('dorsz', 'dozwolone', NULL, NULL, NULL),
('flądra', 'dozwolone', NULL, NULL, NULL),
('halibut świeży', 'dozwolone', NULL, NULL, NULL),
('halibut wędzony', 'dozwolone', NULL, NULL, NULL),
('jesiotr', 'dozwolone', NULL, NULL, NULL),
('karp', 'dozwolone', NULL, NULL, NULL),
('lin', 'dozwolone', NULL, NULL, NULL),
('łosoś świeży', 'dozwolone', NULL, NULL, NULL),
('łosoś wędzony', 'dozwolone', NULL, NULL, NULL),
('makrela wędzona', 'dozwolone', NULL, NULL, NULL),
('miętus', 'dozwolone', NULL, NULL, NULL),
('mintaj', 'dozwolone', NULL, NULL, NULL),
('miruna', 'dozwolone', NULL, NULL, NULL),
('morszczuk', 'dozwolone', NULL, NULL, NULL),
('okoń', 'dozwolone', NULL, NULL, NULL),
('pstrąg świeży', 'dozwolone', NULL, NULL, NULL),
('pstrąg wędzony', 'dozwolone', NULL, NULL, NULL),
('sandacz', 'dozwolone', NULL, NULL, NULL),
('sardynki świeże', 'dozwolone', NULL, NULL, NULL),
('sardynki w oleju/sosie pomidorowym', 'dozwolone', NULL, NULL, NULL),
('sardynki wędzone', 'dozwolone', NULL, NULL, NULL),
('sola', 'dozwolone', NULL, NULL, NULL),
('szczupak', 'dozwolone', NULL, NULL, NULL),
('szprotki wędzone', 'dozwolone', NULL, NULL, NULL),
('szprotki w oleju/w sosie pomidorowym', 'dozwolone', NULL, NULL, NULL),
('śledź', 'dozwolone', NULL, NULL, NULL),
('śledź w occie w zalewie z cebulą', 'dozwolone', NULL, NULL, NULL),
('śledź w occie w zalewie bez cebuli', 'dozwolone', NULL, NULL, NULL),
('śledź w oleju w zalewie z cebulą', 'dozwolone', NULL, NULL, NULL),
('śledź w oleju w zalewie bez cebuli', 'dozwolone', NULL, NULL, NULL),
('tuńczyk świeży', 'dozwolone', NULL, NULL, NULL),
('tuńczyk w puszce w sosie własnym', 'dozwolone', NULL, NULL, NULL),
('tuńczyk w puszce w oleju', 'dozwolone', NULL, NULL, NULL),
('węgorz wędzony', 'dozwolone', NULL, NULL, NULL),
('kalmary', 'dozwolone', NULL, NULL, NULL),
('krewetki', 'dozwolone', NULL, NULL, NULL),
('małże', 'dozwolone', NULL, NULL, NULL),
('ostrygi', 'dozwolone', NULL, NULL, NULL),
('ośmiornice', 'dozwolone', NULL, NULL, NULL),
('przegrzebki (muszle św. Jakuba)', 'dozwolone', NULL, NULL, NULL),
('acerola', 'dozwolone', NULL, NULL, NULL),
('agrest', 'dozwolone', NULL, NULL, NULL),
('ananas', 'dozwolone', NULL, NULL, NULL),
('arbuz', 'umiarkowane', NULL, NULL, NULL),
('aronia', 'dozwolone', NULL, NULL, NULL),
('awokado', 'dozwolone', NULL, NULL, NULL),
('banan niedojrzały', 'dozwolone', NULL, NULL, NULL),
('banan dojrzały', 'umiarkowane', NULL, NULL, NULL),
('borówka amerykańska', 'dozwolone', NULL, NULL, NULL),
('borówka czerwona', 'dozwolone', NULL, NULL, NULL),
('brzoskwinia', 'dozwolone', NULL, NULL, NULL),
('cytryna', 'dozwolone', NULL, NULL, NULL),
('czarna porzeczka', 'dozwolone', NULL, NULL, NULL),
('czereśnia', 'dozwolone', NULL, NULL, NULL),
('czerwona porzeczka', 'dozwolone', NULL, NULL, NULL),
('daktyle suszone', 'umiarkowane', NULL, NULL, NULL),
('dzika róża (owoc)', 'dozwolone', NULL, NULL, NULL),
('figi', 'umiarkowane', NULL, NULL, NULL),
('grapefruit', 'dozwolone', NULL, NULL, NULL),
('granat', 'dozwolone', NULL, NULL, NULL),
('gruszka', 'dozwolone', NULL, NULL, NULL),
('jabłko', 'dozwolone', NULL, NULL, NULL),
('jagody czarne', 'dozwolone', NULL, NULL, NULL),
('jagody goji', 'dozwolone', NULL, NULL, NULL),
('jeżyna', 'dozwolone', NULL, NULL, NULL),
('kaki', 'dozwolone', NULL, NULL, NULL),
('kiwi', 'dozwolone', NULL, NULL, NULL),
('kokos', 'dozwolone', NULL, NULL, NULL),
('liczi', 'dozwolone', NULL, NULL, NULL),
('limonka', 'dozwolone', NULL, NULL, NULL),
('malina', 'dozwolone', NULL, NULL, NULL),
('mandarynka', 'dozwolone', NULL, NULL, NULL),
('mango', 'dozwolone', NULL, NULL, NULL),
('melon', 'dozwolone', NULL, NULL, NULL),
('morela', 'dozwolone', NULL, NULL, NULL),
('morwa', 'dozwolone', NULL, NULL, NULL),
('nektarynka', 'dozwolone', NULL, NULL, NULL),
('papaja', 'dozwolone', NULL, NULL, NULL),
('pigwa', 'dozwolone', NULL, NULL, NULL),
('pomarańcza', 'dozwolone', NULL, NULL, NULL),
('pomelo', 'dozwolone', NULL, NULL, NULL),
('porzeczka', 'dozwolone', NULL, NULL, NULL),
('poziomka', 'dozwolone', NULL, NULL, NULL),
('rabarbar', 'dozwolone', NULL, NULL, NULL),
('rodzynki', 'umiarkowane', NULL, NULL, NULL),
('rokitnik', 'dozwolone', NULL, NULL, NULL),
('smoczy owoc (pitaja)', 'dozwolone', NULL, NULL, NULL),
('śliwka', 'dozwolone', NULL, NULL, NULL),
('śliwka suszona', 'umiarkowane', NULL, NULL, NULL),
('truskawka', 'dozwolone', NULL, NULL, NULL),
('winogrona', 'umiarkowane', NULL, NULL, NULL),
('wiśnia', 'dozwolone', NULL, NULL, NULL),
('żurawina świeża/mrożona', 'dozwolone', NULL, NULL, NULL),
('żurawina suszona', 'umiarkowane', NULL, NULL, NULL),
('batat', 'dozwolone', NULL, NULL, NULL),
('bakłażan', 'umiarkowane', NULL, NULL, NULL),
('boczniak', 'dozwolone', NULL, NULL, NULL),
('bób', 'umiarkowane', NULL, NULL, 'Min 4 h od przyjęcia lewotyroksyny'),
('botwinka/boćwina', 'dozwolone', NULL, NULL, NULL),
('brokuł', 'umiarkowane', NULL, NULL, NULL),
('brukiew', 'umiarkowane', NULL, NULL, NULL),
('brukselka', 'umiarkowane', NULL, NULL, NULL),
('burak', 'dozwolone', NULL, NULL, NULL),
('burak marynowany (w occie)', 'dozwolone', NULL, NULL, NULL),
('cebula', 'dozwolone', NULL, NULL, NULL),
('chrzan', 'dozwolone', NULL, NULL, NULL),
('cukinia', 'dozwolone', NULL, NULL, NULL),
('cykoria', 'dozwolone', NULL, NULL, NULL),
('czosnek', 'dozwolone', NULL, NULL, NULL),
('dynia hokkaido', 'dozwolone', NULL, NULL, NULL),
('dynia piżmowa', 'umiarkowane', NULL, NULL, NULL),
('fasola (nasiona)', 'dozwolone', NULL, NULL, NULL),
('groch łuskany żółty', 'dozwolone', NULL, NULL, NULL),
('grzyby', 'dozwolone', NULL, NULL, NULL),
('imbir', 'dozwolone', NULL, NULL, NULL),
('jarmuż', 'umiarkowane', NULL, NULL, 'wyłącznie gotowany'),
('kalafior', 'umiarkowane', NULL, NULL, 'wyłącznie gotowany'),
('kalarepa', 'umiarkowane', 100.0, 'g', NULL),
('kapusta', 'umiarkowane', 150.0, 'g', NULL),
('kapusta kiszona', 'umiarkowane', 150.0, 'g', NULL),
('karczoch', 'dozwolone', NULL, NULL, NULL),
('kiełki brokuła', 'umiarkowane', NULL, NULL, NULL),
('kiełki rzodkiewki', 'dozwolone', NULL, NULL, NULL),
('kiełki fasoli mung', 'dozwolone', NULL, NULL, NULL),
('koper włoski', 'dozwolone', NULL, NULL, NULL),
('kukurydza z puszki konserwowa', 'dozwolone', NULL, NULL, NULL),
('kurki', 'dozwolone', NULL, NULL, NULL),
('marchew surowa', 'dozwolone', NULL, NULL, NULL),
('marchew gotowana', 'dozwolone', NULL, NULL, NULL),
('ogórek', 'dozwolone', NULL, NULL, NULL),
('ogórek kiszony', 'dozwolone', NULL, NULL, NULL),
('ogórek konserwowy w occie', 'dozwolone', NULL, NULL, NULL),
('oliwki', 'dozwolone', NULL, NULL, NULL),
('pak choi', 'umiarkowane', NULL, NULL, NULL),
('papryka chili', 'umiarkowane', NULL, NULL, NULL),
('papryka czerwona', 'umiarkowane', NULL, NULL, NULL),
('papryka żółta', 'umiarkowane', NULL, NULL, NULL),
('papryka zielona', 'umiarkowane', NULL, NULL, NULL),
('pasternak', 'dozwolone', NULL, NULL, NULL),
('pieczarki', 'dozwolone', NULL, NULL, NULL),
('pieczarki marynowane', 'dozwolone', NULL, NULL, NULL),
('pietruszka korzeń', 'dozwolone', NULL, NULL, NULL),
('pietruszka natka', 'dozwolone', NULL, NULL, NULL),
('pomidor', 'umiarkowane', NULL, NULL, NULL),
('pomidor cherry', 'umiarkowane', NULL, NULL, NULL),
('por', 'dozwolone', NULL, NULL, NULL),
('roszponka', 'dozwolone', NULL, NULL, NULL),
('rzepa', 'dozwolone', NULL, NULL, NULL),
('rukola', 'dozwolone', NULL, NULL, NULL),
('rzodkiew biała', 'dozwolone', NULL, NULL, NULL),
('rzodkiewka', 'dozwolone', NULL, NULL, NULL),
('sałata głowiasta', 'dozwolone', NULL, NULL, NULL),
('sałata lodowa', 'dozwolone', NULL, NULL, NULL),
('sałata rzymska', 'dozwolone', NULL, NULL, NULL),
('seler', 'dozwolone', NULL, NULL, NULL),
('seler naciowy', 'dozwolone', NULL, NULL, NULL),
('soczewica', 'dozwolone', NULL, NULL, NULL),
('soja', 'umiarkowane', NULL, NULL, 'Min 4 h od przyjęcia lewotyroksyny'),
('szczaw', 'dozwolone', NULL, NULL, NULL),
('szczypiorek', 'dozwolone', NULL, NULL, NULL),
('szparagi', 'dozwolone', NULL, NULL, NULL),
('szalotka', 'dozwolone', NULL, NULL, NULL),
('szpinak dojrzały', 'umiarkowane', 30.0, 'g', NULL),
('szpinak baby', 'umiarkowane', 30.0, 'g', NULL),
('topinambur', 'dozwolone', NULL, NULL, NULL),
('zielona fasolka', 'dozwolone', NULL, NULL, NULL),
('zielony groszek', 'dozwolone', NULL, NULL, NULL),
('ziemniak', 'dozwolone', NULL, NULL, NULL),
('ciecierzyca', 'dozwolone', NULL, NULL, NULL),
('groch', 'umiarkowane', NULL, NULL, NULL),
('fasola typu Jaś', 'umiarkowane', NULL, NULL, NULL),
('orzech ziemny', 'umiarkowane', NULL, NULL, NULL),
('masło orzechowe z orzechów ziemnych', 'umiarkowane', NULL, NULL, NULL),
('nasiona pestki słonecznika', 'dozwolone', NULL, NULL, NULL),
('migdały', 'dozwolone', NULL, NULL, NULL),
('pestki dyni', 'dozwolone', NULL, NULL, NULL),
('ziarno kakaowca (czekolada, kakao)', 'dozwolone', NULL, NULL, NULL),
('orzech włoski', 'dozwolone', NULL, NULL, NULL),
('orzech laskowy', 'dozwolone', NULL, NULL, NULL),
('orzech kokosowy (wiórki)', 'dozwolone', NULL, NULL, NULL),
('orzech nerkowca', 'dozwolone', NULL, NULL, NULL),
('orzech brazylijski', 'dozwolone', NULL, NULL, NULL),
('orzech pistacjowy', 'dozwolone', NULL, NULL, NULL),
('orzech makadamia', 'dozwolone', NULL, NULL, NULL),
('orzech pecan', 'dozwolone', NULL, NULL, NULL),
('herbata czarna', 'umiarkowane', NULL, NULL, 'Min 1 h od przyjęcia lewotyroksyny'),
('pokrzywa zwyczajna', 'dozwolone', NULL, NULL, NULL),
('sok pomarańczowy', 'umiarkowane', NULL, NULL, NULL),
('sok pomidorowy', 'umiarkowane', NULL, NULL, NULL),
('napoje energetyczne (energetyki)', 'zakazane', NULL, NULL, NULL),
('napoje czekoladowe', 'umiarkowane', NULL, NULL, NULL),
('napoje kakaowe', 'umiarkowane', NULL, NULL, NULL),
('gorąca czekolada', 'umiarkowane', NULL, NULL, NULL),
('piwo', 'umiarkowane', NULL, NULL, NULL),
('brandy', 'umiarkowane', NULL, NULL, NULL),
('rum', 'umiarkowane', NULL, NULL, NULL),
('wino białe', 'umiarkowane', NULL, NULL, NULL),
('wino różowe', 'umiarkowane', NULL, NULL, NULL),
('wino czerwone', 'umiarkowane', NULL, NULL, NULL),
('wino musujące (prosecco, szampan, cava)', 'umiarkowane', NULL, NULL, NULL),
('wódka', 'umiarkowane', NULL, NULL, NULL),
('spirytus', 'umiarkowane', NULL, NULL, NULL),
('ocet', 'umiarkowane', NULL, NULL, NULL),
('sos sojowy', 'zakazane', NULL, NULL, NULL),
('olej o smaku czosnkowym', 'dozwolone', NULL, NULL, NULL),
('SGF (syrop glukozowo-fruktozowy)', 'umiarkowane', NULL, NULL, NULL),
('sól z antyzbrylaczem', 'umiarkowane', NULL, NULL, NULL);
